### PR TITLE
chore: remove me from CODEOWNERS

### PR DESCRIPTION
**Pull request by ckipp01**
So I'm no longer full-time at the Scala Center and honestly don't have
the time to do much here. I don't feel like my reviews add much on top
of what @adpi2 could just provide, so I'll remove myself from the
CODEOWNERS. If you do still want my feedback for anything, please feel
free to still ping me.

### CODE REVIEW

**Comment by jastice** [comment]
Thank you for your contributions!

Looks like you still need to run `sbt generate` xD

**Comment by agluszak** [comment]
> Looks like you still need to run `sbt generate` xD

Nope, that's because I published a new version x)

Thank you @ckipp01!

**Comment by agluszak** [comment]
Rebasing on main should fix the problem with `sbt generate`

**Comment by ckipp01** [comment]
> Rebasing on main should fix the problem with `sbt generate`

I don't believe so. I'm seeing the v2.1.0-M6 before my commit, so I'm not able to rebase since I'm at HEAD.

**Pull request merged**
