### PR TITLE
Update/org.eclipse.lsp4j.generator 0.19.0

### PR DESCRIPTION
**Pull request by agluszak**

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
Looks good to me. I'd just recommend squashing the commit into one and including basically your comment in the commit itself.

**Comment by ckipp01** [comment]
> I'd just recommend squashing the commit into one and including basically your comment in the commit itself.

@jastice I wish we could have done this before the merge. Now we have a commit that just says `Fix`.

**Comment by jastice** [comment]
No [we don't](https://github.com/build-server-protocol/build-server-protocol/commit/81be42acef5c1a899009d87dd78fcfc7876ae218). Github now squashes by default, and I put the message in the commit

**Comment by ckipp01** [comment]
> No [we don't](https://github.com/build-server-protocol/build-server-protocol/commit/81be42acef5c1a899009d87dd78fcfc7876ae218). Github now squashes by default, and I put the message in the commit

Ah perfect, I wasn't aware it was set up to squash by default.

**Pull request merged**
