### PR TITLE
feat: update to docusaurus2

### PR DESCRIPTION
**Pull request by ckipp01**
This is a follow-up to the work started in
https://github.com/build-server-protocol/build-server-protocol/pull/400 updating docusaurus to v2. This should be a drop in replace and is very similar to the migration that we did in metals. This is also enabling search.

You can play around with the new version [here](https://bsp-ckipp01.vercel.app/).

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
LGTM from my side, thanks for doing this!

**Review by jastice — APPROVED** [review]
Cool, thanks for finishing this!

**Comment by ckipp01** [comment]
There are some things on the dark mode that don't work well. I'll try to address those before merging.

**Comment by jastice** [comment]
Can we merge now?

**Pull request merged**
