### PR TITLE
feat: add optional framework field to scala test classes item

### PR DESCRIPTION
**Pull request by kpodsiad**
Discussed in #296

### CODE REVIEW

**Review by adpi2 — APPROVED** [review]
LGTM

**Comment by odisseus** [comment]
I don't understand how this PR relates to #299. Could you explain?

**Comment by kpodsiad** [comment]
@odisseus it isn't related to the #299, I made a mistake, it is related to #296 - I edited the first comment to fix this.

**Comment by adpi2** [comment]
@kpodsiad `v2.0.0` is already released, so this should be `v2.1.0-M1` maybe?

@jastice Do you think we can cut this release?

**Comment by kpodsiad** [comment]
Oh, I wasn't aware that `v2.0.0` is released, I was misled by what Github shows on the main page.
Screenshot 2022-03-15 at 10 45 40

`v2.1.0-M1` sounds great

**Comment by kpodsiad** [comment]
Hey @jastice! What do you think of `v2.1.0-M1`?

**Comment by jastice** [comment]
> Hey @jastice! What do you think of `v2.1.0-M1`?

Hey, I've been... distracted. Please poke me again if I don't get to this by next week ^^

**Comment by jastice** [comment]
well, it's released, if still relevant

**Comment by kpodsiad** [comment]
It is, thanks @jastice!

**Pull request merged**
