### PR TITLE
Upgrade bsp4s to Monix 3.2.2 and use jsoniter-scala

### PR DESCRIPTION
**Pull request by jvican**
Removes dependency on circe, we now only depend on jsoniter-scala itself
for JSON purposes, which is a library with no third-party dependencies.

### CODE REVIEW

**Comment by jvican** [comment]
Thanks for the review @jastice I hadn't noticed. Do you know why the CI isn't running for PRs?

**Comment by jastice** [comment]
No idea, was it ever setup? Anyway, I opened a PR which will do it.

**Comment by jvican** [comment]
Didn't see it, will fix the issues and rebase. If CI is green I'll merge, is that OK @jastice ?

**Comment by jastice** [comment]
Yup!

**Comment by jvican** [comment]
Superseeded by #175

**Pull request closed without merging**
