### PR TITLE
Fix pull request frequency cron expression in '.scala-steward.conf'

### PR DESCRIPTION
**Pull request by jastice**

### CODE REVIEW

**Review by agluszak — APPROVED** [review]

**Comment by ckipp01** [comment]
This was included in https://github.com/build-server-protocol/build-server-protocol/pull/586, so we can just close this.

**Comment by jastice** [comment]
a bit confusing, but alright!

**Comment by ckipp01** [comment]
Ah well you approved it in the other PR so I thought you were aware, or was there something else that confused you?

**Comment by jastice** [comment]
yeah I was aware (approved it after I made this one), it's just confusing to have it mixed in a version update. But doesn't matter, it's very minor.

**Pull request closed without merging**
