### PR TITLE
use Java 11 in github actions

### PR DESCRIPTION
**Pull request by jastice**
Fixes failing builds due to incompatible class files in xtend generation

### CODE REVIEW

**Comment by adpi2** [comment]
If we use Java 11, will it be still possible to use bsp4 and bsp4j with Java 8?

**Comment by tgodzik** [comment]
> If we use Java 11, will it still be possible to use bsp4 and bsp4j with Java 8?

I think we wouldn't be able to use Java 8, so I would hesitate to merge this :thinking:  We could instead add a separate verify job for JDK 11?

**Comment by jastice** [comment]
I'm trying to figure out how these even broke. #176 would be a good candidate, but reverting to before that commit doesn't fix it. Not even to old 2020 commits. So what is actually going on here?

Meanwhile, we could use JDK11 only for the verify job but not release?

**Comment by tgodzik** [comment]
> I'm trying to figure out how these even broke. #176 would be a good candidate, but reverting to before that commit doesn't fix it. Not even to old 2020 commits. So what is actually going on here?
> 
> Meanwhile, we could use JDK11 only for the verify job but not release?

Probably both jdk 11 and 8 are needed just in case, otherwise the release might fail even if check runs ok.

**Review by olafurpg — COMMENTED** [review]
Can we add a build matrix for the verify job? The release job should continue to run on 8.

**Comment by jastice** [comment]
obsoleted by #185

**Pull request closed without merging**
