### PR TITLE
Cross build all Scala modules for 2.12.x and 2.13.x

### LINKED ISSUE #153: Cross Publish bsp4s
I believe only 2.12 is published a 2.13 would be good.

### PR DESCRIPTION
**Pull request by ckipp01**
**NOTE** ~this is built on top of the work in https://github.com/build-server-protocol/build-server-protocol/pull/175, so you'll want to merge that in first. The only real changes are in this commit: https://github.com/build-server-protocol/build-server-protocol/pull/180/commits/e20a92adbbc875ccdd4c9946eac4f7d3ce45d53a~

Closes #153

### CODE REVIEW

**Comment by ckipp01** [comment]
🤔 it seems the `xtend` stuff starting failing a week ago https://github.com/build-server-protocol/build-server-protocol/runs/2838706798?check_suite_focus=true#step:4:2193 and now it fails every time. I'm not fully sure what is going on there.

**Review by jastice — APPROVED** [review]
There we go!

**Comment by tgodzik** [comment]
@jastice should we release a new tag? We are trying to update monix in Bloop (on the road to 2.13) and seems we need these changes.

**Comment by jastice** [comment]
Sure!

**Comment by tgodzik** [comment]
Thanks!

**Comment by tgodzik** [comment]
@jastice could you add the new tag is possible? I don't have permissions to do that myself. :pray:

**Comment by jastice** [comment]
Done! Publish in process!

**Comment by tgodzik** [comment]
Awesome, thanks! Though I might have called it at a wrong time. There seems to be issues with github actions :sweat:

**Comment by jastice** [comment]
Apparently :(
I'll check again later or tomorrow

**Comment by jastice** [comment]
It seems to have been published despite failing build. does it work for you?

**Comment by tgodzik** [comment]
Haven't checked yet, but it looks alright.

**Pull request merged**
